# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUezoXCv26ydTC3MHpcXD__CYIvofxm6
"""

def rekursif(angka = 0, jumlah = 0 , i = 1):

    if jumlah <= 0 :
        return 0

    else:
        angka = int(input("masukan bilangan ke " + str (i) + ":"))
        if jumlah == 1 :
            return angka

        else:
            i += 1
            return angka + rekursif(angka,jumlah - 1 ,i)

hasil = int(input("masukan jumlah nya : "))
nilai = rekursif (jumlah = hasil)
print("hasil dari penjumlahan adalah : " + str(nilai))

a = int(input("masukan angka: "))
b = int(input("mw di pangkatkan ke berapa: "))

def pangkat(a,b):

    if b >= 1 :
        return a * pangkat(a, b  - 1)

    return a

hasil = pangkat(a, b)
print(f"hasil nya adalah  = {hasil}")